language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - flake8 src/*.py tests/*.py --max-line-length 88
  - black src/*.py tests/*.py
  - pytest --cov=src.bot tests/
after_success:
  - codecov